# Generated by Django 3.1.4 on 2021-01-10 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('posicion', models.CharField(choices=[('1', 'Posición 1, principal'), ('2', 'Posición 2, abajo izquierda'), ('3', 'Posición 3, abajo derecha')], default='1', max_length=1)),
                ('imagen', models.ImageField(upload_to='public/static/uploads/%Y/%m/%d/')),
                ('entradilla', models.CharField(max_length=350, verbose_name='Entradilla')),
                ('cuerpo', tinymce.models.HTMLField(verbose_name='Cuerpo')),
                ('publico', models.BooleanField(default=False, verbose_name='Publicar')),
                ('fecha_creacion', models.DateTimeField(editable=False)),
                ('fecha_modificacion', models.DateTimeField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name_plural': 'Noticias',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioNoticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuerpo', tinymce.models.HTMLField(verbose_name='Cuerpo')),
                ('fecha_creacion', models.DateTimeField(editable=False)),
                ('fecha_modificacion', models.DateTimeField()),
                ('censurado', models.BooleanField(default=False, verbose_name='Censurar')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='news.noticia', verbose_name='Noticia')),
            ],
            options={
                'verbose_name_plural': 'Comentarios',
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
