# Generated by Django 3.1.5 on 2021-01-20 12:23

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarionoticia',
            name='cuerpo',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Cuerpo'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='cuerpo',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Cuerpo'),
        ),
    ]
