# Generated by Django 3.1.3 on 2020-12-01 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemaForo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('descripcion_corta', models.CharField(max_length=300, verbose_name='Descripción corta')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción')),
            ],
            options={
                'verbose_name_plural': 'Temas',
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('cuerpo', tinymce.models.HTMLField(verbose_name='Cuerpo')),
                ('lecturas', models.IntegerField(editable=False, verbose_name='Lecturas')),
                ('fecha_creacion', models.DateTimeField(editable=False)),
                ('fecha_modificacion', models.DateTimeField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foro.temaforo', verbose_name='Tema')),
            ],
            options={
                'verbose_name_plural': 'Publicaciones',
            },
        ),
        migrations.CreateModel(
            name='ComentarioPublicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuerpo', tinymce.models.HTMLField(verbose_name='Cuerpo')),
                ('fecha_creacion', models.DateTimeField(editable=False)),
                ('fecha_modificacion', models.DateTimeField()),
                ('censurado', models.BooleanField(default=False, verbose_name='Censurar')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foro.publicacion', verbose_name='Publicación')),
            ],
            options={
                'verbose_name_plural': 'Comentarios',
            },
        ),
    ]
