# Generated by Django 3.1.4 on 2020-12-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='censurado',
            field=models.BooleanField(default=False, verbose_name='Censurar'),
        ),
    ]
