# Generated by Django 3.1.4 on 2020-12-30 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0002_publicacion_censurado'),
    ]

    operations = [
        migrations.AddField(
            model_name='temaforo',
            name='imagen',
            field=models.ImageField(default='falta', upload_to='public/static/uploads/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
