# Generated by Django 3.1.4 on 2020-12-31 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0004_auto_20201231_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='lecturas',
            field=models.IntegerField(verbose_name='Lecturas'),
        ),
    ]
