# Generated by Django 3.1.6 on 2021-02-05 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0008_auto_20210120_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacion',
            options={'ordering': ['-fecha_creacion'], 'verbose_name_plural': 'Hilos'},
        ),
    ]
