# Generated by Django 3.1.3 on 2020-12-01 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('entradilla', tinymce.models.HTMLField(verbose_name='Entradilla')),
                ('cuerpo', tinymce.models.HTMLField(verbose_name='Cuerpo')),
                ('publico', models.BooleanField(default=False, verbose_name='Publicar')),
                ('fecha_creacion', models.DateTimeField(editable=False)),
                ('fecha_modificacion', models.DateTimeField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name_plural': 'Articulos',
            },
        ),
        migrations.CreateModel(
            name='TemaArticulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('descripcion_corta', models.CharField(max_length=300, verbose_name='Descripción corta')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción')),
                ('lecturas', models.IntegerField(editable=False, verbose_name='Lecturas')),
            ],
            options={
                'verbose_name_plural': 'Temas',
            },
        ),
        migrations.CreateModel(
            name='ComentarioArticulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuerpo', tinymce.models.HTMLField(verbose_name='Cuerpo')),
                ('fecha_creacion', models.DateTimeField(editable=False)),
                ('fecha_modificacion', models.DateTimeField()),
                ('censurado', models.BooleanField(default=False, verbose_name='Censurar')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.articulo', verbose_name='Artículo')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name_plural': 'Comentarios',
            },
        ),
        migrations.AddField(
            model_name='articulo',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.temaarticulo', verbose_name='Tema'),
        ),
    ]
