# Generated by Django 3.1.3 on 2020-12-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_temaarticulo_lecturas'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(default='hola.jpg', upload_to='uploads/% Y/% m/% d/'),
            preserve_default=False,
        ),
    ]
