# Generated by Django 3.1.3 on 2020-12-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_articulo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(upload_to='public/static/uploads/%Y/%m/%d/'),
        ),
    ]
