# Generated by Django 3.1.4 on 2020-12-15 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201215_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarioarticulo',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='blog.articulo', verbose_name='Artículo'),
        ),
    ]
