# Generated by Django 3.1.5 on 2021-01-20 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201229_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentarioarticulo',
            options={'ordering': ['fecha_creacion'], 'verbose_name_plural': 'Comentarios de artículos'},
        ),
        migrations.AlterModelOptions(
            name='temaarticulo',
            options={'verbose_name_plural': 'Temas de artículos'},
        ),
    ]
