# Generated by Django 3.1.5 on 2021-01-20 12:23

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210120_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='cuerpo',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Cuerpo'),
        ),
        migrations.AlterField(
            model_name='comentarioarticulo',
            name='cuerpo',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Cuerpo'),
        ),
    ]
