# Generated by Django 3.1.6 on 2021-02-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210120_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulo',
            options={},
        ),
        migrations.AddField(
            model_name='articulo',
            name='users_notified',
            field=models.BooleanField(default=False, editable=False, verbose_name='Han sido los usuarios notificados?'),
        ),
    ]
