# Generated by Django 3.1.4 on 2021-01-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_perfil_frase_inspiradora'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='desactivar',
            field=models.BooleanField(default=False, verbose_name='Cuenta desactivada'),
        ),
    ]
