# Generated by Django 3.1.4 on 2021-01-03 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_perfil_desactivar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='desactivar',
            new_name='cuenta_desactivada',
        ),
    ]
