# Generated by Django 3.1.6 on 2021-02-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_auto_20210105_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='nuevo_articulo',
            field=models.BooleanField(default=True, verbose_name='Notificar con nuevo artículo'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nuevo_comentario',
            field=models.BooleanField(default=True, verbose_name='Notificar con nuevo comentario'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nuevo_evento',
            field=models.BooleanField(default=True, verbose_name='Notificar con nuevo evento'),
        ),
    ]
