# Generated by Django 3.1.6 on 2021-02-12 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_auto_20210212_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='nuevo_articulo',
            new_name='mail_on_nuevo_articulo',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='nuevo_comentario',
            new_name='mail_on_nuevo_comentario',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='nuevo_evento',
            new_name='mail_on_nuevo_evento',
        ),
    ]
